### ISSUE TITLE
Representing vector layers using tiled assets

### ISSUE THREAD

**Issue by thomafred** [stac-extensions/tiled-assets#7]
Hi there!

This STAC extension seems useful for representing vector map tiles. However the best-practices document discourages using STAC for this purpose:

https://github.com/radiantearth/stac-spec/blob/master/best-practices.md#representing-vector-layers-in-stac

Do you have any experience with this?

**Comment by constantinius** [comment]
@thomafred I personally have no experience on this.

Regarding the section you mentioned: I would argue that vector tiles are not necessarily comparable with Shapefiles/SQLite databases and are much more geared towards data exchange, instead of storing or data management.

I could see that `tiled-assets` would work quite well with vector tiles to be honest.

**Comment by thomafred** [comment]
Cool!

We will experiment a little with this and get back to you
